import AppFooter from "@/components/AppFooter";
import { CoreProvider } from "@/providers/CoreProvider";
import type { Metadata } from "next";
import "../styles/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex flex-col justify-center items-center w-full">
        <CoreProvider>
          <div className="flex flex-col w-full max-w-screen-sm">
            {children}
            <AppFooter />
          </div>
        </CoreProvider>
      </body>
    </html>
  );
}
